### PR TITLE
nix 1.11.8 -> 1.11.9

### PR DESCRIPTION
**Pull request by alicebob**
Key comes from here:

http://nixos.org/releases/nix/nix-1.11.9/nix-1.11.9-x86_64-linux.tar.bz2.sha256

Otherwise untested.

### CODE REVIEW

**Comment by benley** [comment]
thanks!

**Comment by alicebob** [comment]
Hmm, I did not bump the version in metadata.rb :/

**Comment by benley** [comment]
If you send another PR I'll merge it quickly.

Also if you actively use this cookbook would you like to be a maintainer? I don't actually use Chef for work anymore so I haven't had much time to work on it...

**Comment by alicebob** [comment]
I'll think about it. My goal is to get rid of Chef, so... :)

**Pull request merged**
